### ISSUE TITLE
Return 1 if cancelled

### ISSUE THREAD

**Issue by vaygr** [cedricbu/dmoji#1]
Hey, thanks for such a smart idea on implementing this.

It'd be helpful if dmoji returned 1 in case of cancellation (<kbd>Esc</kbd>). dmenu does.

My use case is I want to autotype from clipboard if something was selected. Maybe it can be considered a feature in the future. But for now this workaround should work.

**Comment by cedricbu** [comment]
Good point!
I made the change, I hope it helps.

**Comment by cedricbu** [comment]
(commit: https://github.com/cedricbu/dmoji/commit/adddb828e32481b649a69b6e06673160cf60253c)

**Comment by vaygr** [comment]
Thanks, that's great! Could you please take a look at #2 and maybe tag 0.5 if nothing else is planned soon?

I'm maintaining `dmoji` [package](https://aur.archlinux.org/packages/dmoji) at AUR, which requires quite a few patches to build.

**Comment by cedricbu** [comment]
Done and done.
Good to know, I will try not breaking backward compatibility in the future

**Comment by vaygr** [comment]
:tada:
